<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Prime Number Counter">
    <meta name="author" content="Daniel P. Purdy">

    <title>Prime Number Counter</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <!-- other css for layout theme -->
    <?php echo $this->tag->stylesheetLink("css/main.css"); ?>
    <?php echo $this->tag->stylesheetLink("css/icomoon.css"); ?>
    <?php echo $this->tag->stylesheetLink("css/fancyfont.css"); ?>
    
    <link href='//fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>	
 
    <!-- javascript -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <?php echo $this->tag->javascriptInclude("js/modernizr.custom.js"); ?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-spy="scroll" data-offset="0" data-target="#navbar-main">
      <div id="navbar-main">
      <!-- Fixed navbar -->
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon icon-stack" style="font-size:30px; color:#3498db;"></span>
              </button>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                        <li><a href="/index">Home</a></li>
            </div><!--/.nav-collapse -->
          </div><!-- contaier -->
        </div><!-- navbar -->
      </div><!-- navbar main -->
  
      <!-- ==== HEADERWRAP ==== -->
      <div id="headerwrap" id="home" name="home">
        <header class="clearfix">
          <p><strong>Prime Numbers</strong></p>
        </header>
      </div><!-- /headerwrap -->


      <?php echo $this->getContent() ?>

      <footer class="footer navbar-fixed-bottom navbar-inverse">
	<div class="container">
  	    &copy D.P. Purdy, 2016
        </div>
      </footer>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

